### ISSUE TITLE
Bootstrap 2.0.2

### ISSUE THREAD

**Issue by rmoriz** [blanchardjeremy/hyde-bootstrap#3]
Hi!

Any plans to upgrade to the latest Bootstrap?

thank you.

Roland

**Comment by blanchardjeremy** [comment]
Thanks for checking in.

Yeah, I do have an intention of eventually supporting Bootstrap 2.0.2, but since I"m not actively building any Hyde sites right now, I don't have a lot of time set aside for such work.

For hyde-bootstrap 2.0 (which will support bootstrap 2), I want to use https://github.com/auzigog/jinja-bootstrap as a base for the templates. I'm not quite sure the way to make that really easy and smooth for Hyde since it will be a pip dependency that they need to have for it to work out.

Here are the options I see for bringing jinja-bootstrap in as the base for hyde-bootstrap:
- Ask folks to pip install jinja-bootstrap (into their normal system or into a virtualenv)
- Ask folks to download a zip with jinja-bootstrap and put it in a specific place in their hyde folder (not good for them being able to update easily)
- Have a git submodule repository inside hyde-bootstrap that clones jinja-bootstrap... This might be a good option for most folks since they just want to get Hyde up and running quickly, not deal with more packages to install.

Does anyone have any feedback on any of those?

**Comment by navilan** [comment]
@auzigog - `pip install` is probably the smoothest option there. I will be adding better ways for using base layouts in hyde soon.

**Comment by blanchardjeremy** [comment]
Closing this because #4 has been merged in.
